""""""""""""""""""""""
PHILOSOPHER BOT DISCORD 1.2
---------------
Criado por Caio Madeira (@sudomaidera)
Disponível no Discord e no Twitter!
2020

"""""""""""""""""""""""
from PIL import Image

filosofo = [
    Image.open('Img/char/adamsmith.png'),
    Image.open('Img/char/alanturing.png'),
    Image.open('Img/char/aristoteles.png'),
    Image.open('Img/char/bakunin.png'),
    Image.open('Img/char/castro.png'),
    Image.open('Img/char/chaplin.png'),
    Image.open('Img/char/che.png'),
    Image.open('Img/char/curie.png'),
    Image.open('Img/char/dalailama.png'),
    Image.open('Img/char/descartes.png'),
    Image.open('Img/char/FUKO.png'),
    Image.open('Img/char/jesus.png'),
    Image.open('Img/char/karnal.png'),
    Image.open('Img/char/lenin.png'),
    Image.open('Img/char/MANDELA.png'),
    Image.open('Img/char/maquiavel.png'),
    Image.open('Img/char/martin.png'),
    Image.open('Img/char/marx.png'),
    Image.open('Img/char/mussolini.png'),
    Image.open("Img/char/neto.png"),
    Image.open("Img/char/neymar.png"),
    Image.open("Img/char/niet.png"),
    Image.open("Img/char/pascal.png"),
    Image.open("Img/char/platao.png"),
    Image.open("Img/char/rousseau.png"),
    Image.open("Img/char/stalin.png"),
    Image.open("Img/char/winston.png"),
    Image.open("Img/char/albert.png"),
    Image.open("Img/char/anyrand.png"),
    Image.open("Img/char/bauman.png"),
    Image.open("Img/char/camus.png"),
    Image.open("Img/char/clarice.png"),
    Image.open("Img/char/dilma.png"),
    Image.open("Img/char/fiodor.png"),
    Image.open("Img/char/freud.png"),
    Image.open("Img/char/hannah.png"),
    Image.open("Img/char/hawk.png"),
    Image.open("Img/char/jobs.png"),
    Image.open("Img/char/kimjonun.png"),
    Image.open("Img/char/mao.png"),
    Image.open("Img/char/newton.png"),
    Image.open("Img/char/olavo.png"),
    Image.open("Img/char/schop.png"),
    Image.open("Img/char/simone.png"),
    Image.open("Img/char/socrates.png"),
    # -------------------------------
    Image.open("Img/char/putin.png"),
    Image.open("Img/char/aristoteles_2.png"),
    Image.open("Img/char/ada.png"),
    Image.open("Img/char/amoedo.png"),
    Image.open("Img/char/bolsonaro.png"),
    Image.open("Img/char/deus.png"),
    Image.open("Img/char/juliocesar.png"),
    Image.open("Img/char/kimjongil.png"),
    Image.open("Img/char/malcomx.png"),
    Image.open("Img/char/nicolau_czar.png"),
    Image.open("Img/char/pele.png"),
    Image.open("Img/char/platao_2.png"),
    Image.open("Img/char/rosa.png"),
    # ------------------------------
    Image.open("Img/char/alexandre.png"),
    Image.open("Img/char/assange.png"),
    Image.open("Img/char/clovis.png"),
    Image.open("Img/char/copernico.png"),
    Image.open("Img/char/dumont.png"),
    Image.open("Img/char/durkheim.png"),
    Image.open("Img/char/goulart.png"),
    Image.open("Img/char/lacerda.png"),
    Image.open("Img/char/machado.png"),
    Image.open("Img/char/oscar.png"),
    Image.open("Img/char/sinatra.png"),
    Image.open("Img/char/suntzu.png"),
    Image.open("Img/char/tiradentes.png"),
    Image.open("Img/char/washington.png"),
    Image.open("Img/char/monark.png"),
    Image.open("Img/char/shelby.png"),
    Image.open("Img/char/veiohavan.png"),
    Image.open("Img/char/renatorusso.png"),
    Image.open("Img/char/michael_scott.png"),
    Image.open("Img/char/lucifer.png"),
    Image.open("Img/char/dwight.png"),
]